### ISSUE TITLE
Error in TemplateImpl.fixClonedDom in IE11

### ISSUE THREAD

**Issue by rictic** [webcomponents/webcomponentsjs#497]
Seeing this in a project's tests on attempting to update from v0.7.20 to v0.7.21

`t.parentNode` is null or undefined, leading to an error when we try to call `replaceChild` on it in the last line of `fixClonedDom`:

``` javascript
    TemplateImpl.fixClonedDom = function(clone, source) {
      // these two lists should be coincident
      var s$ = source.querySelectorAll(TEMPLATE_TAG);
      var t$ = clone.querySelectorAll(TEMPLATE_TAG);
      for (var i=0, l=t$.length, t, s; i<l; i++) {
        s = s$[i];
        t = t$[i];
        if (this.decorate) {
          this.decorate(s);
        }
        t.parentNode.replaceChild(s.cloneNode(true), t);
      }
    };
```

Here: https://github.com/webcomponents/webcomponentsjs/blob/84c6c670d1fb95ea848995339d952b96c2e8fe6a/src/Template/Template.js#L185

**Comment by sorvell** [comment]
It'd be great to get a snippet of the template that's causing the error. Also, is this browser specific? (for example is it limited to IE?)

**Comment by kapouer** [comment]
I'm seeing an error in fixClonedDom too, but sooner, on "source", which is sometimes a text node,
and which does not support querySelectorAll as such.
It's triggered by `myTextNode.cloneNode(true)` AFAICT.

**Comment by kapouer** [comment]
Also, reverting to version 0.7.20 fixes the issue.

**Comment by robbecker-wf** [comment]
I am getting this error only in IE11 (and not IE10!)
![image](https://cloud.githubusercontent.com/assets/6053699/13858516/056a9cd2-ec4d-11e5-9c74-9b6d72903a2f.png)
I've narrowed it down to when there is a template tag in the template for a custom element. It can be any template tag (bare, dom-if, dom-bind). Here's the simplest snippet that reproduces it for me in IE11:
```
<dom-module id="double-template">
    <template>
        <template>
            <div>hi</div>
        </template>
    </template>
    <script>
        Polymer({is: 'double-template'});
    </script>
</dom-module>
```
If you comment out the inner template, then no error.

**Comment by robbecker-wf** [comment]
perhaps there is an async problem here when the template is stamped into the local DOM ?

**Comment by PaulHMason** [comment]
Is there a fix for this yet? It completely breaks the Polymer input elements in IE11. The `dom-if` below doesn't work in IE11 (it's the same thing that breaks the Polymer `paper-input-container` element).

````
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes">
    <title>input error</title>
    <script src="../../webcomponentsjs/webcomponents-lite.js"></script>
    <link rel="import" href="../../polymer/polymer.html" />

</head>
<body unresolved>
    <template is="dom-bind" id="app">
        <template is="dom-if" if="[[canShow]]">
          <div>Template</div>
        </template>
    </template>
    
    <script>
        var app = document.getElementById("app");
        app.canShow = true;
    </script>
</body>
</html>

````

**Comment by kapouer** [comment]
https://github.com/webcomponents/webcomponentsjs/commit/7d7fad8ac258a10257e692a57b1b542860d03725 should fix it.

**Comment by PaulHMason** [comment]
Ah - the update doesn't seem to coming down as a dependency with Polymer though.

**Comment by kapouer** [comment]
You could run this or something similar in a postinstall npm script:
https://gist.github.com/kapouer/6837881b8658bb4270583cd0dbb37486

On a later update, the patch will simply fail and you'll know it's time to remove the script.

**Comment by ankon** [comment]
7d7fad8 does not seem to fix it for me -- at least on a Windows 7 with IE11 I'm still hitting the issue[*]. What I'm also not sure is how this is supposed to be fixing it: I my case `clone` and `source` are `DocumentFragment` instances, which do have a `querySelectorAll` method.

If element-ness was intended, wouldn't it be better to check with `source.nodeType === Node.ELEMENT_NODE`?

[*] ... Oddly enough, I cannot trigger the issue with Windows 10 and IE11.

**Comment by ankon** [comment]
Reading more closely, it seems the two issues are unrelated: `source` not having a `querySelectorAll` method (@kapouers issue) would be avoided by the 7d7fad8 fix, but the original one of this ticket (`t.parentNode` being `null`) would not.

**Comment by noahlaux** [comment]
+1 on releasing this, as we experience similar issue using the polyfill in combination with knockout.js

**Comment by davemackintosh** [comment]
Still seeing this issue in version `0.7.21`.

**Comment by azakus** [comment]
@davemackintosh Do you mean `0.7.22`?

**Comment by davemackintosh** [comment]
Sorry, something went crazy with my build system and for some reason it never copied the updated version across to the staging environment. All good from me 👍

**Comment by rictic** [comment]
v0.7.22 fixes this for the original code that I was reporting for this issue (sorry I wasn't able to get a simple repro)

**Comment by ianmclean2011** [comment]
@kapouer i'm seeing an error similar to the one you merged a fix for above (#501) but for the clone instead of the source. Would it make sense to add a line for the clone as well? 

`TemplateImpl.fixClonedDom = function(clone, source) {
       // do nothing if cloned node is not an element
       if (!source.querySelectorAll || !clone.querySelectorAll) return;`

I'm new to webcomponentsjs, and not really sure what is happening in the above section. I just know that I had a IE11 error, and it was fixed by using the change above.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
